### ISSUE TITLE
0.5.2 + 0.5.3 noop version can not be downloaded

### ISSUE THREAD

**Issue by Bodo1981** [patrickfav/under-the-hood#4]
releaseCompile(group: "at.favre.lib.hood", name: "hood-core", version: "0.5.2", classifier: "noop", ext: "aar", transitive: true)

does not work:

Gradle sync failed: Could not find hood-core-noop.aar (at.favre.lib.hood:hood-core:0.5.2).
					Searched in the following locations:
					https://jcenter.bintray.com/at/favre/lib/hood/hood-core/0.5.2/hood-core-0.5.2-noop.aar
					Consult IDE log for more details (Help | Show Log)

**Comment by patrickfav** [comment]
These are all on bintray, but I will see what the problem is.

**Comment by patrickfav** [comment]
So this seems to be an syncing issue from bintray to jcenter (since merge 2 repos, it seems hood-core will not be synced).

See
https://jcenter.bintray.com/at/favre/lib/hood/hood-core/
vs.
https://jcenter.bintray.com/at/favre/lib/hood/hood-extended/

I'm in contact with the support team and I hope they can relink it.



In the meanwhile you could use the private repo

repositories {
    maven {
        url  "https://dl.bintray.com/patrickfav/maven" 
    }
}
     
or use maven central (but noop seems to not be synced)

https://repo.maven.apache.org/maven2/at/favre/lib/hood/hood-core/
https://repo.maven.apache.org/maven2/at/favre/lib/hood/hood-extended/

**Comment by patrickfav** [comment]
So problem should be resolved, needed direct contact to JFrog's twitter to get someboday to fix it.
Please report back if you have any more issues
